name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 0.1.0)'
        required: true
        type: string

permissions:
  contents: write
  discussions: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.get_version.outputs.version }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      
      - name: Get version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"
      
      - name: Extract changelog
        id: changelog
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          if [ -f CHANGELOG.md ]; then
            # Extract changelog section for this version
            sed -n "/## \[$VERSION\]/,/## \[/p" CHANGELOG.md | sed '$d' > release-notes.md
            if [ ! -s release-notes.md ]; then
              echo "No changelog entry found for version $VERSION, using placeholder"
              echo "Release $VERSION" > release-notes.md
            fi
          else
            echo "Release $VERSION" > release-notes.md
          fi
          cat release-notes.md
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Context-Sync v${{ steps.get_version.outputs.version }}
          body_path: release-notes.md
          draft: false
          prerelease: ${{ contains(steps.get_version.outputs.version, 'alpha') || contains(steps.get_version.outputs.version, 'beta') || contains(steps.get_version.outputs.version, 'rc') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    name: Build Windows
    needs: create-release
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.19.0
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: app/pnpm-lock.yaml
      
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            app/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('app/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      
      - name: Install dependencies
        run: |
          cd app
          pnpm install --frozen-lockfile
      
      - name: Build and package
        run: |
          cd app
          pnpm run make
        env:
          NODE_ENV: production
      
      - name: List output files
        run: |
          Get-ChildItem -Path app\out\make -Recurse -File
      
      - name: Find Windows artifacts
        id: find_windows
        shell: pwsh
        run: |
          $files = Get-ChildItem -Path app\out\make\squirrel.windows -Include *.exe,*.nupkg -Recurse | Select-Object -ExpandProperty FullName
          $fileList = $files -join "`n"
          echo "files=$fileList" >> $env:GITHUB_OUTPUT
          echo "Found files:"
          echo $fileList
      
      - name: Upload Windows Squirrel installer
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.create-release.outputs.version }}
          files: ${{ steps.find_windows.outputs.files }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    name: Build macOS
    needs: create-release
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.19.0
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: app/pnpm-lock.yaml
      
      - name: Install dependencies
        run: |
          cd app
          pnpm install --frozen-lockfile
      
      - name: Build and package
        run: |
          cd app
          pnpm run make
        env:
          NODE_ENV: production
      
      - name: List output files
        run: |
          find app/out/make -type f
      
      - name: Find macOS artifacts
        id: find_macos
        run: |
          files=$(find app/out/make/zip/darwin -name "*.zip" -type f | tr '\n' ' ')
          echo "files=$files" >> $GITHUB_OUTPUT
          echo "Found files: $files"
      
      - name: Upload macOS ZIP
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.create-release.outputs.version }}
          files: ${{ steps.find_macos.outputs.files }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    name: Build Linux
    needs: create-release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.19.0
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: app/pnpm-lock.yaml
      
      - name: Install dependencies
        run: |
          cd app
          pnpm install --frozen-lockfile
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm
      
      - name: Build and package
        run: |
          cd app
          pnpm run make
        env:
          NODE_ENV: production
      
      - name: List output files
        run: |
          find app/out/make -type f
      
      - name: Find Linux artifacts
        id: find_linux
        run: |
          deb_files=$(find app/out/make -name "*.deb" -type f)
          rpm_files=$(find app/out/make -name "*.rpm" -type f)
          all_files="$deb_files $rpm_files"
          echo "files=$all_files" >> $GITHUB_OUTPUT
          echo "Found files: $all_files"
      
      - name: Upload Linux packages
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.create-release.outputs.version }}
          files: ${{ steps.find_linux.outputs.files }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  validate-release:
    name: Validate Release Assets
    needs: [create-release, build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    
    steps:
      - name: Check release assets
        run: |
          echo "✅ Release v${{ needs.create-release.outputs.version }} created successfully"
          echo "All platform builds completed"
